# Generated by Django 5.2.7 on 2025-11-02 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='messages',
            field=models.JSONField(default=list, help_text='List of message objects'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='expertise',
            field=models.JSONField(default=list, help_text='List of expertise areas'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL', null=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='order_priority',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='title',
            field=models.CharField(help_text="e.g., 'Senior Partner', 'Associate'", max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='order_priority',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
