# Generated by Django 5.2.7 on 2025-11-10 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_aiconversation_messages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_title', models.CharField(help_text="e.g., 'CEO of Tech Corp', 'Individual Client'", max_length=255)),
                ('client_company', models.CharField(blank=True, max_length=255, null=True)),
                ('testimonial_text', models.TextField(help_text='The testimonial content')),
                ('client_image_url', models.URLField(blank=True, help_text='Cloudinary URL for client photo', null=True)),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('case_type', models.CharField(blank=True, help_text="e.g., 'Blockchain Law', 'AI Regulation'", max_length=100, null=True)),
                ('order_priority', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
                'ordering': ['order_priority', '-created_at'],
                'indexes': [models.Index(fields=['order_priority'], name='testimonial_order_p_ccc734_idx'), models.Index(fields=['is_active', 'is_featured'], name='testimonial_is_acti_2a5935_idx')],
            },
        ),
    ]
