# Generated by Django 5.2.7 on 2025-11-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('context_used', models.JSONField(default=dict, help_text='What context was injected (blog_posts, associates, etc)')),
                ('user_clicked_action', models.BooleanField(default=False, help_text='Did user click any action button/link in response')),
                ('action_clicked', models.CharField(blank=True, help_text='What action was clicked', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Analytics',
                'verbose_name_plural': 'Chat Analytics',
                'db_table': 'chat_analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='chat_analyt_created_370827_idx'), models.Index(fields=['session_id'], name='chat_analyt_session_25e3e6_idx')],
            },
        ),
    ]
