# Generated by Django 5.2.7 on 2025-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Most Outstanding Student Judge'", max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('grant_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('grant', 'Grant'), ('award', 'Award'), ('fellowship', 'Fellowship')], default='grant', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Grant amount in Naira', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('short_description', models.TextField(help_text='Brief description for listing cards', max_length=300)),
                ('full_description', models.TextField(help_text='Full description with details')),
                ('eligibility_criteria', models.JSONField(default=list, help_text='List of eligibility requirements')),
                ('how_to_apply', models.TextField(help_text='Application instructions')),
                ('requirements', models.JSONField(default=list, help_text='List of required documents/materials')),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('application_url', models.URLField(blank=True, help_text='External application link if any', null=True)),
                ('guidelines', models.JSONField(default=list, help_text='List of guidelines for applicants')),
                ('image_url', models.URLField(blank=True, help_text='Main grant/scholarship image', null=True)),
                ('banner_image_url', models.URLField(blank=True, help_text='Banner image for detail page', null=True)),
                ('target_audience', models.CharField(help_text="e.g., 'Law Students', 'Student Judges'", max_length=255)),
                ('target_institutions', models.JSONField(default=list, help_text='List of eligible institutions')),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('announcement_date', models.DateField(blank=True, help_text='When winners will be announced', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open for Applications'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('order_priority', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('social_links', models.JSONField(default=dict, help_text='Social media links for the grant (twitter, linkedin, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grant/Scholarship',
                'verbose_name_plural': 'Grants & Scholarships',
                'db_table': 'grants',
                'ordering': ['order_priority', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='grants_slug_82dbc0_idx'), models.Index(fields=['status'], name='grants_status_de9c13_idx'), models.Index(fields=['is_active', 'is_featured'], name='grants_is_acti_654819_idx'), models.Index(fields=['application_deadline'], name='grants_applica_4288b4_idx')],
            },
        ),
    ]
