# Generated by Django 5.2.7 on 2025-11-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grant amount (optional)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='eligibility_criteria',
            field=models.JSONField(blank=True, default=list, help_text='List of eligibility requirements'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='full_description',
            field=models.TextField(blank=True, default='', help_text='Full description with details'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='guidelines',
            field=models.JSONField(blank=True, default=list, help_text='List of guidelines for applicants'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='how_to_apply',
            field=models.TextField(blank=True, default='', help_text='Application instructions'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of required documents/materials'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Brief description for listing cards', max_length=300),
        ),
        migrations.AlterField(
            model_name='grant',
            name='target_audience',
            field=models.CharField(blank=True, default='', help_text="e.g., 'Law Students', 'Student Judges'", max_length=255),
        ),
        migrations.AlterField(
            model_name='grant',
            name='target_institutions',
            field=models.JSONField(blank=True, default=list, help_text='List of eligible institutions'),
        ),
    ]
