# Generated by Django 5.2.7 on 2026-02-09 11:47

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_simplify_grant_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('ai_law', 'AI Law & Regulation'), ('blockchain', 'Blockchain & Crypto'), ('data_privacy', 'Data Privacy'), ('tech_contracts', 'Tech Contracts'), ('ip', 'Intellectual Property'), ('corporate', 'Corporate Law'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Cloudinary URL', null=True)),
                ('order_priority', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation Service',
                'verbose_name_plural': 'Consultation Services',
                'db_table': 'consultation_services',
                'ordering': ['order_priority', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='consultatio_slug_84a758_idx'), models.Index(fields=['is_active', 'is_featured'], name='consultatio_is_acti_11b5d2_idx'), models.Index(fields=['category'], name='consultatio_categor_455151_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=api.models.generate_booking_reference, help_text='Booking reference number', max_length=50, unique=True)),
                ('custom_service_description', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=50)),
                ('client_company', models.CharField(blank=True, max_length=255)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('paystack_access_code', models.CharField(blank=True, max_length=100)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_associate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='api.associate')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.consultationservice')),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'db_table': 'consultation_bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='consultatio_referen_63b4d1_idx'), models.Index(fields=['paystack_reference'], name='consultatio_paystac_20207d_idx'), models.Index(fields=['status'], name='consultatio_status_a7c75a_idx'), models.Index(fields=['client_email'], name='consultatio_client__8afc71_idx'), models.Index(fields=['-created_at'], name='consultatio_created_bd446c_idx'), models.Index(fields=['preferred_date'], name='consultatio_preferr_9ad185_idx')],
            },
        ),
    ]
